version: "2"
services:
  mapseries:
    build: .
    restart: always
    environment:
      GITHUB_CLIENT_ID: be39fea131a1ca0521d8
      GITHUB_CLIENT_SECRET: cef0f1d3e97f257ae5e3ae811b44a9bf0aaf010c
    ports:
      - 8080:8080
      - 8787:8787
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/eduda/tmp/postgres-data:/var/lib/postgresql/data:z
