version: "2"
services:
  mapseries:
    image: mapseries:latest
    restart: always
    environment:
      GITHUB_CLIENT_ID: be39fea131a1ca0521d8
      GITHUB_CLIENT_SECRET:
    ports:
      - 8080:8080
      - 8787:8787
    volumes:
      - ../log:/mapseries_logs
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../postgre:/var/lib/postgresql/data
